import AppKit
import Foundation

public enum ClipboardDefaults {
    public static let snapshotByteLimit = 33_554_432

    public static let transientMarkers: [String] = [
        "org.nspasteboard.TransientType",
        "org.nspasteboard.AutoGeneratedType",
        "org.nspasteboard.ConcealedType",
        "com.agilebits.onepassword",
        "de.petermaurer.TransientPasteboardType",
        "com.typeit4me.clipping.data",
    ]

    public static let unrestorableTypes: Set<String> = Set(transientMarkers).union([
        "com.apple.pasteboard.promised-file-url",
        "com.apple.pasteboard.promised-file-content",
        "com.apple.filepromise",
        "com.apple.pasteboard.file-promise-content",
        "com.stairways.keyboardmaestro.concealed",
    ])
}

public enum PasteboardWriteResult: Sendable, Equatable {
    case success(changeCount: Int)
    case rejected
}

public protocol PasteboardBackend: Sendable {
    var changeCount: Int { get }
    var itemCount: Int { get }
    func typeIdentifiers(ofItemAt index: Int) -> [String]
    func materializeData(itemAt index: Int, typeIdentifier: String) -> Data?
    func replaceItems(_ items: [[String: Data]]) -> PasteboardWriteResult
}

public final class GeneralPasteboard: PasteboardBackend, @unchecked Sendable {
    private let pasteboard: NSPasteboard

    public init(_ pasteboard: NSPasteboard = .general) {
        self.pasteboard = pasteboard
    }

    public var changeCount: Int { pasteboard.changeCount }

    public var itemCount: Int { pasteboard.pasteboardItems?.count ?? 0 }

    public func typeIdentifiers(ofItemAt index: Int) -> [String] {
        guard let items = pasteboard.pasteboardItems, items.indices.contains(index) else { return [] }
        return items[index].types.map(\.rawValue)
    }

    public func materializeData(itemAt index: Int, typeIdentifier: String) -> Data? {
        guard let items = pasteboard.pasteboardItems, items.indices.contains(index) else { return nil }
        return items[index].data(forType: NSPasteboard.PasteboardType(rawValue: typeIdentifier))
    }

    public func replaceItems(_ items: [[String: Data]]) -> PasteboardWriteResult {
        pasteboard.clearContents()
        let objects = items.map { types -> NSPasteboardItem in
            let item = NSPasteboardItem()
            for (type, data) in types {
                item.setData(data, forType: NSPasteboard.PasteboardType(rawValue: type))
            }
            return item
        }
        guard pasteboard.writeObjects(objects as [NSPasteboardWriting]) else { return .rejected }
        return .success(changeCount: pasteboard.changeCount)
    }
}
